services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "zxc"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"