
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "zxc"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge:latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Contraseña12345678"
    ports:
      - 1433:1433
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    command: /opt/mssql_scripts/run-initialization.sh
    stdin_open: true
    volumes:
      - ./mssql_scripts:/opt/mssql_scripts
