openapi: "3.0.2"
info:
  title: "WorkerService API"
  description: "Manages a collection of objects. The collection must store Worker class objects"
  version: "0.1"
  contact:
    name: "WorkerService API"
    url: "https://elephants.org/workerapi"
    email: "k.arseny03@gmail.com"
  license:
    name: "CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)"
    url: "https://elephants.org/price"

servers:
  - url: 'https://localhost:8080/api/v0.1'

paths:
  /api/worker/get/{id}:
    get:
      summary: "Get worker by id"
      description: "Get worker by id"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "0b4cd6d5-5a8b-4aa7-8f4a-49b74a733a90"

      responses:
        '200':
          description: "Return all information about worker"
          content:
            application/json:
              schema:
                $ref: "./Models.yml#/components/schemas/Worker"


        '400':
          description: Invalid parameters supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 400
                  message:
                    type: string
                    example: Invalid parameters supplied
                  time:
                    type: string
                    format: date-time
                    example: "2024-10-01T16:06:38.397Z"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 500
                  message:
                    type: string
                    example: Internal server error
                  time:
                    type: string
                    format: date-time
                    example: "2024-10-01T16:06:38.397Z"