version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: worker-postgres
    environment:
      - POSTGRES_DB=worker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./Infrostructure/scripts/initdb.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - worker-network

  worker-service-ejb:
    build:
      context: .
      dockerfile: wildfly/Dockerfile
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres
    networks:
      - worker-network

  worker-service-web:
    image: openjdk:17-oracle
    volumes:
      - ./worker-web-ebedded/target/worker-web-ebedded-0.0.1-SNAPSHOT.jar:/web.jar
    command: [ "java", "-jar", "web.jar" ]
    ports:
      - "1516:1516"
    networks:
      - worker-network

networks:
  worker-network:
    driver: bridge